<a href="https://colab.research.google.com/github/chetana-H/Applications-of-python-programming-in-DA-and-ML/blob/master/Day_3_session_2_example_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas Example**

# **Write a Pandas program to create and display a one-dimensional array using series containing even numbers upto 10**

In [1]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8,10]) 
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


# **Write a Pandas program to convert a Panda module Series to Python list and its type.**


In [2]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


# **Write a Pandas program to add, subtract, multiple and divide two Pandas Series.**
# **Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]**

In [3]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# **Write a Pandas program to compare the elements of the two Pandas Series.**
# **Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]**


In [4]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


## **Write a Pandas program to convert a dictionary to a Pandas series.**
# Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800} **bold text**


In [5]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


# **Write a Pandas program to convert a NumPy array to a Pandas series.**
Sample NumPy array: d1 = [10, 20, 30, 40, 50]


In [6]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


Write a Pandas program to change the data type of the given Series into numeric
['100', '200', 'python', '300.12', '400']



In [7]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


# **Write a Pandas program to convert a given Series to an array.**

In [8]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


# **Write a Pandas program to sort a given Series.**

In [9]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


# **Write a Pandas program to add some data to an existing Series.**

In [10]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


# **Write a Pandas program to create a subset of a given series based on value and condition.**

In [11]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


# **Write a Pandas program to change the order of index of a given series.**

In [12]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


# **Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.**


In [13]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


# **Write a Pandas program to get the elements of an array values into column-wise.**
Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

In [14]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


# **Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).**

In [16]:
import pandas as pd 
import numpy as np 
import io
from google.colab import files 
uploaded = files.upload()
df2 = pd.read_csv(io.BytesIO(uploaded['movies_metadata.csv']))
print("Columns of the DataFrame:")
print(df.columns)

KeyboardInterrupt: ignored

## Write a Pandas program to sort the DataFrame based on country from dataset of movie_metadata.csv**

In [17]:
import pandas as pd 
import numpy as np 
import io

from google.colab import files 
uploaded = files.upload()
df2 = pd.read_csv(io.BytesIO(uploaded['movies_metadata.csv']))
print("sorted by country")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('country')
print("DataFrame based on release date.")
print(result)


KeyboardInterrupt: ignored

# **Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).**

In [18]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)

FileNotFoundError: ignored

# **Write a Pandas program to display the first 10 rows of the DataFrame.**

In [19]:
import pandas as pd
df = pd.read_csv('/home/cyborg/Desktop/Data analytics/programs/movie_metadata.csv')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

FileNotFoundError: ignored

# **Numpy Examples**

# **Write a NumPy program to generate five random numbers from the normal distribution.**



In [20]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[ 0.45150887 -0.02415831  0.39405702 -1.40037151 -0.58986037]


# **Write a NumPy program to generate six random integers between 10 and 30**

In [21]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[19 24 11 23 19 14]


# Write a NumPy program to create a 3x3x3 array with random values.



In [22]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[5.38582503e-01 2.33186172e-02 1.09101519e-01]
  [9.46432214e-01 4.08478680e-01 4.89962637e-01]
  [5.45818749e-01 8.53326227e-01 1.33389939e-01]]

 [[6.03869564e-01 2.30201825e-01 5.24285124e-01]
  [3.61915365e-01 3.84705130e-04 1.74383891e-01]
  [6.86441386e-01 3.49195459e-01 1.35179830e-01]]

 [[1.42437769e-01 1.79039729e-01 9.12317230e-02]
  [6.85973646e-02 3.92888249e-01 6.94242114e-01]
  [4.50831964e-01 8.78397882e-01 8.03298085e-01]]]


# **Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.**


In [23]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.76407706 0.54046511 0.04149142 0.7088956  0.99517089]
 [0.46373034 0.61915327 0.74017221 0.79455906 0.14260864]
 [0.47687721 0.43004567 0.66653943 0.88800411 0.33648431]
 [0.15933329 0.85753861 0.11950765 0.2693078  0.45272187]
 [0.60777926 0.66415113 0.98280767 0.15985788 0.29289514]]
Minimum and Maximum Values:
0.04149142331947919 0.9951708867648879


# **Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.**



In [24]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.815667   0.28541276 0.30573487 0.52520924]
 [0.53123358 0.64060117 0.39110569 0.50707851]
 [0.64942374 0.75170272 0.81570138 0.85815482]
 [0.77057781 0.74998233 0.86333884 0.23806272]
 [0.05772467 0.38208659 0.24684435 0.13125804]
 [0.56541233 0.71507988 0.34956241 0.23029422]
 [0.05247756 0.20122488 0.2829431  0.05726417]
 [0.56796827 0.88521797 0.47646989 0.95829623]
 [0.458627   0.74084564 0.90539188 0.11879268]
 [0.34696357 0.9159352  0.20332423 0.30475737]]
First 5 rows of the above array:
[[0.815667   0.28541276 0.30573487 0.52520924]
 [0.53123358 0.64060117 0.39110569 0.50707851]
 [0.64942374 0.75170272 0.81570138 0.85815482]
 [0.77057781 0.74998233 0.86333884 0.23806272]
 [0.05772467 0.38208659 0.24684435 0.13125804]]
First 3 columns of the above array:
[[0.815667   0.28541276 0.30573487 0.52520924]
 [0.53123358 0.64060117 0.39110569 0.50707851]
 [0.64942374 0.75170272 0.81570138 0.85815482]
 [0.77057781 0.74998233 0.86333884 0.23806272]
 [0.05772467 0.3820

# **Write a NumPy program to shuffle numbers and find permutation between 0 and 10 (inclusive).**


In [25]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[5 4 2 7 0 8 3 6 9 1]
Same result using permutation():
[9 2 0 4 3 1 5 6 8 7]


# **Write a NumPy program to create a random integer nos of size 10 and sort it.**


In [26]:
import numpy as np
x=np.arange(10)
np.random.randint(x)
print (x)


ValueError: ignored

# **Write a NumPy program to create a random integer nos of size 10 and sort it.**

In [ ]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)
