<a href="https://colab.research.google.com/github/chetana-H/Applications-of-python-programming-in-DA-and-ML/blob/master/Day_3_session_2_exercise_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000**
tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [1]:
import pandas as pd
import numpy as np
l1=([i for i in range(1,1000) if i%2==0])
s1=pd.Series(l1)
print(s1)

0        2
1        4
2        6
3        8
4       10
      ... 
494    990
495    992
496    994
497    996
498    998
Length: 499, dtype: int64


# **Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type**

In [2]:
import pandas as pd
import numpy as np
s1=pd.Series([x for x in range(1000,2000) if x%5==0])
print(s1)


0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


# **Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]**


In [3]:
import pandas as pd
import numpy as np
l1=([i for i in range(1,100) if i%2==0])
s1=pd.Series(l1)
l2=([i for i in range(1,100) if i%2!=0])
s2=pd.Series(l2)
print("add s= ")
print(s1+s2)
print("sub s= ",s1+s2)
print("mul s=",s1*s2)
print("div s=",s1/s2)


add s= 
0       3.0
1       7.0
2      11.0
3      15.0
4      19.0
5      23.0
6      27.0
7      31.0
8      35.0
9      39.0
10     43.0
11     47.0
12     51.0
13     55.0
14     59.0
15     63.0
16     67.0
17     71.0
18     75.0
19     79.0
20     83.0
21     87.0
22     91.0
23     95.0
24     99.0
25    103.0
26    107.0
27    111.0
28    115.0
29    119.0
30    123.0
31    127.0
32    131.0
33    135.0
34    139.0
35    143.0
36    147.0
37    151.0
38    155.0
39    159.0
40    163.0
41    167.0
42    171.0
43    175.0
44    179.0
45    183.0
46    187.0
47    191.0
48    195.0
49      NaN
dtype: float64
sub s=  0       3.0
1       7.0
2      11.0
3      15.0
4      19.0
5      23.0
6      27.0
7      31.0
8      35.0
9      39.0
10     43.0
11     47.0
12     51.0
13     55.0
14     59.0
15     63.0
16     67.0
17     71.0
18     75.0
19     79.0
20     83.0
21     87.0
22     91.0
23     95.0
24     99.0
25    103.0
26    107.0
27    111.0
28    115.0
29    119.0
30    123

# **Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.**
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000

In [4]:
import pandas as pd
import numpy as np
s1=pd.Series([i for i in range(1,1000) if i%7==0])
s1=pd.Series([i for i in range(1,1000) if i%11==0])
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(s2)):
  print(i," ",s1[i]==s2[i])
print("Greater than:")
for i in range(len(s2)):
  print(i," ",s1[i]>s2[i])
print("Less than:")
for i in range(len(s2)):
  print(i," ",s1[i]<s2[i])
print("not Equal")
for i in range(len(s2)):
  print(i," ",s1[i]!=s2[i])


Compare the elements of the said Series:
Equals:
0   False
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
Greater than:
0   True
1   True
2   True
3   True
4   True
5   True
6   True
7   True
8   True
9   True
10   True
11   True
12   True
13   True
14   True
15   True
16   True
17   True
18   True
19   True
20   True
21   True
22   True
23   True
24   True
25   True
26   True
27   True
28   True
29   True
30   True
31   True
32   True
33   True
34   True
35   True
36   True
37   True
38   True
39   True
40   Tr

#**Write a Pandas program to convert a NumPy array to a Pandas series. 
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000 ** 


In [5]:
import numpy as np
import pandas as pd
np_array = np.array([i for i in range(1,1000) if i%10==0])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360
 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540
 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720
 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900
 910 920 930 940 950 960 970 980 990]
Converted Pandas series:
0      10
1      20
2      30
3      40
4      50
     ... 
94    950
95    960
96    970
97    980
98    990
Length: 99, dtype: int64


# **Write a Pandas program to convert a given Series to an array.**
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [6]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100','200','300','400','500','python','300.2','400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6        300.2
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.2' '400' 'is' 'great'
 'language']


# **Write a Pandas program to sort a given Series.**
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]



In [7]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100','200','300','400','500','python','300.2','400','is','great','language'])
print(s1)
s2=s1.sort_values()
print(s2)


0          100
1          200
2          300
3          400
4          500
5       python
6        300.2
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6        300.2
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


# **Write a Pandas program to create a subsets of a given series based on value and condition.**
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [8]:
import pandas as pd
import numpy as np
d1=np.array([i for i in range(1,1000) if i%10==0])
print(d1)
print("subset 1")
subset1=d1[d1%7==0]
print(subset1)
print("subset2")
subset2=d1[d1%5==0]
print(subset2)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360
 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540
 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720
 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900
 910 920 930 940 950 960 970 980 990]
subset 1
[ 70 140 210 280 350 420 490 560 630 700 770 840 910 980]
subset2
[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360
 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540
 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720
 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900
 910 920 930 940 950 960 970 980 990]


# **Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000**


In [9]:
import pandas as pd
l=[]
for val in range(0,1001):
  if val > 1: 
        for n in range(2, val//2 + 2): 
            if (val % n) == 0: 
                break
            else: 
                if n == val//2 + 1: 
                    l.append(val)
s = pd.Series(data = l)
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        3
1        5
2        7
3       11
4       13
      ... 
162    971
163    977
164    983
165    991
166    997
Length: 167, dtype: int64
Mean of the said Data Series:
455.8383233532934
Standard deviation of the said Data Series:
297.0201672063572


# **Write a Pandas program to get the elements of an array values into column-wise.**
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [10]:
import pandas as pd
l1=([i for i in range(0,1001) if i%7!=0 and i%2!=0])
p1=pd.Series(l1)
l2=([i for i in range(0,1001) if i%2==0 and i%5!=0])
p2=pd.Series(l2)
l3=([i for i in range(0,1001) if i%2!=0 and i%3!=0])
p3=pd.Series(l3)
print(len(l1),len(l2),len(l3))
for i in range(len(l3)):
  df = pd.DataFrame({'X':p1, 'Y':p2,'Z':p3})
print(df)


429 400 333
       X     Y     Z
0      1   2.0   1.0
1      3   4.0   5.0
2      5   6.0   7.0
3      9   8.0  11.0
4     11  12.0  13.0
..   ...   ...   ...
424  991   NaN   NaN
425  993   NaN   NaN
426  995   NaN   NaN
427  997   NaN   NaN
428  999   NaN   NaN

[429 rows x 3 columns]


# **1Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.**

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

# **Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).**

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv', error_bad_lines=False)
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

**Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields**

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv', error_bad_lines=False)
result = df[['title', 'genres']]
print("Details of title and genres:")
print(result)

# **Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv**

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('movie_metadata.csv')
print("sorted by country")
result = df.sort_values('country')
print(result)
print("sorted by lang")
result = df.sort_values('language')
print(result)

# **Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of 50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)**



In [14]:
import pandas as pd
df = pd.DataFrame({'roll number':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],'marks':[20,22,23,24,25,26,27,12,13,15,23,24,23,21,12,13,14,15,30,24,25,26,27,28,29,30,22,22,22,22,23,23,23,23,23,23,24,24,24,25,26,26,27,27,27,27,27,26,27,23]})
print(df.mean())
print(df.std())
print(df.min())
print(df.max())
df.to_csv('python_marks',index=False)
df1 = pd.read_csv('python_marks')
print(df1)
print(df1.mean())
print(df1.std())
print(df1.min())
print(df1.max())



roll number    25.50
marks          23.14
dtype: float64
roll number    14.577380
marks           4.558061
dtype: float64
roll number     1
marks          12
dtype: int64
roll number    50
marks          30
dtype: int64
    roll number  marks
0             1     20
1             2     22
2             3     23
3             4     24
4             5     25
5             6     26
6             7     27
7             8     12
8             9     13
9            10     15
10           11     23
11           12     24
12           13     23
13           14     21
14           15     12
15           16     13
16           17     14
17           18     15
18           19     30
19           20     24
20           21     25
21           22     26
22           23     27
23           24     28
24           25     29
25           26     30
26           27     22
27           28     22
28           29     22
29           30     22
30           31     23
31           32     23
32           33     2

# **Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable.**


In [18]:
import numpy as np
x = np.random.random((4,4))
print(x)
print("2nd and 3rd rows of the above array:")
y= x[1:3, :]
print(y)

[[0.70286176 0.88981431 0.47011984 0.07376072]
 [0.61932372 0.340894   0.57680736 0.90426086]
 [0.20602414 0.39538621 0.04736668 0.32023874]
 [0.41910304 0.4544466  0.65790295 0.0940684 ]]
2nd and 3rd rows of the above array:
[[0.61932372 0.340894   0.57680736 0.90426086]
 [0.20602414 0.39538621 0.04736668 0.32023874]]


# **Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.**

In [17]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.65866352 0.41308787 0.13603836 0.61184175 0.52860908 0.15804645
  0.41721776 0.5749968  0.39571682 0.24856936]
 [0.34980405 0.79754028 0.86524026 0.3619062  0.37763875 0.16928801
  0.91150629 0.46445289 0.43305842 0.80866886]
 [0.1745719  0.80537973 0.23890352 0.25873505 0.94235834 0.85175327
  0.35696216 0.93869754 0.74085562 0.15340534]
 [0.15109166 0.57442854 0.17388898 0.55214303 0.05117881 0.1359865
  0.46885115 0.22373856 0.55368606 0.45970821]
 [0.13928969 0.67948888 0.17426895 0.11216936 0.6857622  0.47063123
  0.16997799 0.85308104 0.06835746 0.86017621]
 [0.51070582 0.04558765 0.00965374 0.38840155 0.37718168 0.13023999
  0.11871491 0.91631125 0.85947222 0.13943058]
 [0.82639988 0.95821703 0.52572935 0.96151851 0.35687774 0.34276399
  0.55334746 0.16789827 0.57875265 0.63491108]
 [0.39372223 0.57858867 0.9546167  0.06188617 0.26704766 0.72147803
  0.19679039 0.15786231 0.45197986 0.67111989]
 [0.33629119 0.85414124 0.09378185 0.77526873 0.23347705 0.995189

# **.Write a NumPy program to generate 8 random integers between 100 and 300**


In [16]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[189 288 260 236 158 186 120 284]


# **Write a NumPy program to create a random integer nos of size 20 and sort it.**

In [15]:
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[13 11  0  1 12 10  9  6 18  5 15  8  3 17 19  2 14 16  7  4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
